# -*- coding: utf-8 -*-
"""Income Distribution and Household Demographics.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HIlb6EpWXmW_3sxm3nEmsSSrGJT3NR3W

##Project Overview: Analyzing Income Distribution and Household Demographics
### 🎯 Objective
As a data analyst for a social-economic research organization, your core mission is to decode the demographic and financial realities of regional households. Instead of just looking at raw numbers, this project requires applying mathematical rigor and statistical concepts to uncover the true stories hidden in the data.

###Through this analysis:

* **Categorize Data**: Classify variables correctly to determine the right analytical approach.

* **Calculate Descriptive Statistics**: Establish the central tendencies (mean, median, mode) and dispersion (variance, standard deviation) of household wealth and family structures.

* **Analyze Distribution Properties**: Go beyond basic averages by evaluating the skewness (the asymmetry of income distribution) and kurtosis (the presence of outliers or "heavy tails" in the data) to understand the gap between different economic tiers.
"""

# First import all library that use in our analysis.
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Mount the google drive, because our data present in the google drive.
from google.colab import drive
drive.mount('/content/drive')

# Upload the file from the drive and convert in dataframe.
df = pd.read_excel('/content/drive/MyDrive/Household_Demographics_Data.xlsx')

"""###Basic Data inspection

"""

# Checking the first 100 row of the data set.
print("The  last 10 Rows Of the Dataset.")
df.head(10)

# Last 10 rows of the dataset.
print("The  last 10 Rows Of the Dataset.")
df.tail(10)

# Checking the shape of the dataset.
shape = df.shape
print(f"The number of row  is {shape[0]} and column is {shape[1]}")

# Checking the data type of all columns.
print("The Data Type Of All Columns.")
print("\n",df.dtypes)

from IPython.core.display import Markdown
# Identify the column data in numerical and categorical.
data_types_df = pd.DataFrame({
    'Column_name': df.columns,
    'Data_type' : df.dtypes.astype(str)
})

# Map the python datatype to analyze classification for clearly.
type_mapping = {
    'object': 'Categorical',
    'int64': 'Numerical',
    'float64': 'Numerical'
}
data_types_df['Analytical classification'] = data_types_df['Data_type'].map(type_mapping)


# Display as a clean table.
display(Markdown("### Data Set variable classification"))
data_types_df

"""##Central Tendency"""

# Calculate the mean, median and mode of the Household Income and Age.
# 1. Calculate the mean of the Household age and income.
household_income_mean = df['Household_Income'].mean()
household_Age_mean = df['Age_of_Household_Head'].mean()

# 2. Mode of the both cloumn.
household_income_mode = df['Household_Income'].mode()
household_Age_mode = df['Age_of_Household_Head'].mode()

# 3. Median of the columns.
household_income_median = df['Household_Income'].median()
household_Age_median = df['Age_of_Household_Head'].median()

# 4 Diaplay all the central tendency.
print(f"The mean of the Household income is:{household_income_mean}")
print(f"The mean of the Household Age is:{household_Age_mean}")
print(f"The mode of the Household income is:{household_income_mode}")
print(f"The mode of the Household Age is:{household_Age_mode}")
print(f"The median of the Household income is:{household_income_median}")
print(f"The median of the Household Age is:{household_Age_median}")

"""### Measure of dispersion

"""

# Calculate the Range, Varience and standard deviation of the Household income.
# 1. Calculate the range of the Household income column.
min = df['Household_Income'].min()
max = df['Household_Income'].max()
range = max- min
print(f"The range of the Household income is: {range}")

# 2. Variance of the Household income column.
variance = df['Household_Income'].var()
print(f"The variance of the Household income is: {variance:.1f}")

# 3. Standard deviation  of the house hold income column.
std  = df['Household_Income'].std()
print(f"The standard deviation of the house hold income is: {std:.0f}")

# Calculate the Inter Quartile range for the Household income column.
# Step 1 : fisrt we have to calculate the 1st and 3rd quartile.
q1 = df['Household_Income'].quantile(0.25)
q3 = df['Household_Income'].quantile(0.75)

# Step 2 : Calculate the IQR.
# Formula for IQR = q3 - q1
IQR = q3-q1
print(f"The Inter quartile range  for this househol income is: {IQR} ")

# Step 3: Calclate the upper and the lower bound.
upper_bound = q3 + 1.5* IQR
lower_bound = q1 - 1.5 * IQR

"""## Distributions

"""

# Plot a Histogram to see the pread of the Household Income.
# Set the figure size.
plt.figure(figsize = (10, 6))
sns.set_theme(style= "whitegrid")
# Create the histogram.
sns.histplot(data=df, x='Household_Income', bins=30, kde=True, color = '#1f4E78')

# Add title and labels for storytelling.
plt.title("Distribution of Household_Income", fontsize = 14 , fontweight = 'bold')
plt.xlabel("Monthly Income", fontsize = 12)
plt.ylabel("Frequency (Number of household)", fontsize = 12)

# Display the plot.
plt.show()

#  fit a Gaussian normal distribution curve.
from scipy.stats import norm

income_data = df['Household_Income']

# Calculate the parameter mu and the std.
mu, std = norm.fit(income_data)

# Set the plot.
plt.figure(figsize=(10, 6))
sns.set_theme(style="whitegrid")

# Make the histplot.
sns.histplot(income_data, bins=30, stat="density", color ='#1F4E78', alpha = 0.6)

# Generate the normal gausian curve.
xmin, xmax = plt.xlim()
x = np.linspace(xmin, xmax, 100)
p = norm.pdf(x, mu, std)

#  Plot the curve over the histogram
plt.plot(x, p, 'k', linewidth=2, label=f'Gaussian Fit mu={mu:,.0f}, sigma={std:,.0f}')

plt.title('Gaussian Normal Curve Fit - Household Income', fontsize=14, fontweight='bold')
plt.xlabel('Monthly Income', fontsize=12)
plt.ylabel('Density', fontsize=12)
plt.legend()
plt.show()

# Calculate the skewness and the kurtosis value for the household Income.
from scipy.stats import skew, kurtosis

# Calculate the skewness of Household Income column.
skewness = df['Household_Income'].skew()

# Claculate the kurtosis for the Household column.
kurtosis = df['Household_Income'].kurtosis()

# Structure the result.
shape_matrics = pd.DataFrame({
    'Metric' : ['Skewness', 'Kurtosis'],
    'Calculated_value': [f"{skewness:.4f}", f"{kurtosis:.4f}"],
    'Interpretation': ['Positive value indicates a right-skewed distribution (tail extends to higher incomes).',
        'Positive value indicates a leptokurtic distribution (heavier tails and more extreme outliers than a normal curve).'
    ]
})

# Display the Table.
display(Markdown("**Distribution Shape Metrics: Household Income**"))
display(Markdown(shape_matrics.to_markdown(index=False)))

"""## Data Categorization.

"""

# Plot the box plot or histogram to compare the household income across different education level and urbans\ rural.
# Plot the histogram to compare the house hold income and the eduction level.
# set the plot.
plt.figure(figsize=(8, 6))
sns.set_theme(style='whitegrid')

# Plot the boxplot.
sns.boxplot(data=df, x='Education_Level', y='Household_Income', palette="Blues", order=['Primary', 'Secondary', 'Graduate', 'Post-Grad'])

# Add title for better storytelling.
plt.title('Income Distribution by Education Level', fontsize=14, fontweight='bold')
plt.xlabel('Education Level', fontsize=12)
plt.ylabel('Monthly Household Income', fontsize=12)
plt.tight_layout()
plt.show()

# set the plot.
plt.figure(figsize=(8, 6))
sns.set_theme(style='whitegrid')

# Create the box plot.
sns.boxplot(data=df, x='Urban_Rural', y='Household_Income', palette='Set2')

# Add title and formating for better storytelling.
plt.title("Income Distribution :Urban vs Rural", fontsize=14, fontweight='bold')
plt.xlabel("Location Type", fontsize=14)
plt.ylabel("Monthly Household_Inocme", fontsize=14)
plt.tight_layout()
plt.show()

"""## Visualizations

"""

# Box plot for comparing the family size by Education Level.
# Set the plot.
plt.figure(figsize=(8, 6))
sns.set_theme(style= "whitegrid")

# Create the box plot.
sns.boxplot(data=df, x='Education_Level', y= 'Family_Size',order=['Primary', 'Secondary', 'Graduate', 'Post-Grad'])

# Add title and label for the better storytelling.
plt.title("Family Size VS Education Level", fontsize=14, fontweight= 'bold')
plt.xlabel("Education Level", fontsize=14)
plt.ylabel("Family Size", fontsize=14)
plt.tight_layout()
plt.show()

from IPython.utils.path import errno
# Distribution Curve for age vs Income.
# Set up a side-by-side charting space
fig= plt.subplots(figsize=(10, 6))
sns.set_theme(style="whitegrid")

# Create the line plot.
sns.lineplot(
    data=df,
    x='Age_of_Household_Head',
    y='Household_Income',
    color='#1F4E78',
    errorbar=('ci', 0.95),
    linewidth=2.5
)

# Add title and the formating for better storytelling.
plt.title('Average Household Income by Age (with 95% Confidence Interval)', fontsize=14, fontweight='bold')
plt.xlabel('Age of Household Head', fontsize=12)
plt.ylabel('Monthly Household Income', fontsize=12)

# Display the final chart
plt.tight_layout()
plt.show()

